# примеры API-запросов

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "potato5",
  "description": "Лучшие potato на рынке"
}

###

# получение продуктов
GET {{baseUrl}}/products/?page=3
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/1/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?title=cucumber
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "new3",
  "positions": [
    {
      "product": 6,
      "quantity": 250,
      "price": 120.50
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/4/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?id=2
Content-Type: application/json
